spring.cloud.azure.cosmos.endpoint=${AZURE_COSMOSDB_ENDPOINT}
spring.cloud.azure.cosmos.database.name=MultiAgentDB
spring.ai.azure.openai.api-key=${AZURE_OPENAI_APIKEY}
spring.ai.azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT}
spring.ai.azure.openai.embedding.options.deployment-name=${AZURE_OPENAI_EMBEDDINGDEPLOYMENTID}
spring.ai.azure.openai.chat.options.deployment-name=gpt-4o
spring.ai.azure.openai.deployment-name=gpt-4o
spring.ai.azure.openai.model=gpt-4o
spring.autoconfigure.exclude=\
  org.springframework.ai.autoconfigure.vectorstore.cosmosdb.CosmosDBVectorStoreAutoConfiguration

